### ISSUE TITLE
Modify the code to allow users to name the measurement file before exporting it

### ISSUE THREAD

**Issue by aron-adc** [DCBIA-OrthoLab/Q3DCExtension#18]
@jcfr @bpaniagua @luciacev 
Hi, 

When Q3DC exports the quantitative measurements of either distances or angles, it does not allow users to change the name of the file to be exported. The current version always saves distance    measurements as “distance”  and angular measurements as  “angle”. 
Can you please edit the code to allow users to name the measurement file before exporting it?

Currently , when the user has to perform multiple rounds of measurements, when we click on the “export” option  for the second round, a WARNING message appears saying: “File…/angle(or distance).csv already exists! Do you want to replace it?” This message appears even when there is no file with the same name on that folder. 
 
In the third round of measurements and exporting, this warning message appears twice, and so on depending on how many rounds of data exporting you are performing.

It does not happen with the first round of measurements, if we restart the software. However, it is time consuming to have to restart the software to continue.

Thank you in advance for your help.

**Comment by jcfr** [comment]
Closing. This has been fixed.
