### ISSUE TITLE
Scipy manual installation no longer needed for latest Slicer

### ISSUE THREAD

**Issue by jamesobutler** [DCBIA-OrthoLab/Q3DCExtension#22]
As of https://github.com/Slicer/Slicer/commit/47deb76d7556e40de4e25e585c4b24a63a153da5 Scipy is included in the default Slicer build.  Therefore you can remove the need to install scipy within the extension as long as users haven't manually uninstalled it.
https://github.com/DCBIA-OrthoLab/Q3DCExtension/blob/1f02acbc7e5e9ed1bb4bfeefddd680406c1621e0/Q3DC/Q3DC.py#L11-L16

This action would be valid for current Slicer 4.11 preview releases, but if trying to maintain compatibility with Slicer 4.10 stable, this would not work.  With a new stable release coming soon, the latest stable won't require the manual installation of scipy.

**Comment by JEHoctor** [comment]
Thanks for making this issue, James. I'm going to add the suggestion you made [here](https://discourse.slicer.org/t/problem-q3dc-extension/11374/5) to this issue as well.

**Comment by jcfr** [comment]
Update of integration of networkx will be revisited while fixing https://github.com/DCBIA-OrthoLab/Q3DCExtension/issues/24

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/DCBIA-OrthoLab/Q3DCExtension/pull/25
