### ISSUE TITLE
Using scroll wheel while placing a landmark places multiple landmarks

### ISSUE THREAD

**Issue by JEHoctor** [DCBIA-OrthoLab/Q3DCExtension#28]
When adding a landmark to the scene with the button beneath the model and landmarks selectors, scrolling to better view the model causes landmarks to be placed.

**Comment by JEHoctor** [comment]
I am assigning this issue to myself since, as @aron-adc noted, it is similar to #43.

**Comment by allemangD** [comment]
Closing. This was resolved with https://github.com/DCBIA-OrthoLab/Q3DCExtension/pull/55, but the issue was not linked.
