### ISSUE TITLE
Allow editing markup name based on pre-defined lists

### ISSUE THREAD

**Issue by aruellas** [DCBIA-OrthoLab/Q3DCExtension#4]
_For sake of clarity, the original issue title and description have been edited by @jcfr_

**Goal**: Support annotating what each fiducial is anatomically and make this information readily apparent in the fcsv saved after computing distance, angle, ....

* The pre-defined lists are described below as "legends".
* These legends are not standard measurements.
* Each entries of the legend table include a `Landmark short name` and `Landmark Description`
* Users should be able to provide their own legends
* User may be able to rename placed ficucials based on provided legend

## Proposed implementation

After selecting a fiducial using:

![image](https://user-images.githubusercontent.com/219043/84186965-59987480-aa5f-11ea-882e-32bf06afe201.png)

The user will be able to click on any entry of the table listed under "Landmark Legend":

![image](https://user-images.githubusercontent.com/219043/84186919-484f6800-aa5f-11ea-93da-80a548c2de60.png)

Then the corresponding fiducial name displayed in the interface and saved in the different measurement files will be updated based on the "short name" (e.g `N` will be used instead of `Nasion`)

Notes:
* the table represented in the user interface are generated based on the content of a The module interface will be updated to include tables generated based a given csv file like the following:

```csv
Region,Landmark,Name
CRANIAL BASE,Ba,Basion
CRANIAL BASE,S,Sella
CRANIAL BASE,N,Nasion
NASOMAXILLARY COMPLEX,A,A-point
NASOMAXILLARY COMPLEX,ANS,Anterior Nasal Spine
[...]
MANDIBLE,B,B-point
MANDIBLE,Pog,Pogonion
[...]
```

## Example of "legend"

![image](https://cloud.githubusercontent.com/assets/14109035/9658119/d523398a-5214-11e5-9119-5148a0bec309.png)

## References

* [Fiducial Legend for Q3DC.docx](https://drive.google.com/open?id=1XtZK82CGh_T88uLjltJPRnS7seXX3UOJ)
* https://en.wikipedia.org/wiki/Cephalometric_analysis

**Comment by aruellas** [comment]
it should be editable according to each project

**Comment by aruellas** [comment]
They are not standard measurements and it should be nice if the users could edit the table adding and removing landmarks for their projects. The example I uploaded is just some measurements for one specific study. Maybe in the future we will be able to add measurements to describe and standardize a 3D analysis trying to replace the 2D available nowadays.

**Comment by aruellas** [comment]
![image](https://cloud.githubusercontent.com/assets/14109035/9752989/11c323cc-5685-11e5-8b58-27b788a10cdf.png)

**Comment by JEHoctor** [comment]
From discussion with Lucia 2020-04-20:

The goal of this feature request is to annotate what each fiducial is anatomically, and make this information readily apparent in the fcsv. Lucia will provide me with a list of landmark names and descriptions.

**Comment by luciacev** [comment]
@aruellas @JEHoctor @bpaniagua @jcfr 

Hi Antonio 
James is working to address the issue  you posted in 2015 of  adding a cephalometry legend to the Q3DC landmark numbers following your request in 2015. We understand it should be editable according to each project, but I am trying to make a relatively complete   fiducial list . I will send you the list by email. Thoughts? Thanks!

**Comment by jcfr** [comment]
Closing. This is has been address by @JEHoctor in #30
