### ISSUE TITLE
Support deleting rows from measurement table

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/Q3DCExtension#40]
From  @marcelagurgel :

> When doing a linear or angular measurement, after click on  "calculate" button, we are not able to undo the measurement or delete it. Sometimes I have measurements made by mistake, and I just can delete it after saving in excel software. It would be easier to delete it right away in Slicer when the mistake is done.

This should be done after addressing https://github.com/DCBIA-OrthoLab/Q3DCExtension/issues/42

**Comment by allemangD** [comment]
I meant to link PR #63 to issue #42 instead of this one. I'll address this issue next, since it was directly blocked by #42.
