### ISSUE TITLE
Re-factor handling of measurement files

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/Q3DCExtension#42]
In the current implementation, "creation of tables used to list measurements" and "saving of these measurement in files" have their own implementation.

Since Slicer now provide build blocks allowing to easily perform these operation (and much more), the module should be refactored to leverage these.

Suggest approach:

* Create one `vtkMRMLTableNode` per type of measurements:
  * to allow filtering, each would have a different attribute: `q3dc.measurements.distance`,  `q3dc.measurements.angle`, ...
  * the node would have `SaveWithScene` set to `False`

* Create a `qMRMLTableView` for each

* Add buttons allowing to:
  * "Export" or "Import" measurement files
  * Delete rows

**Comment by allemangD** [comment]
Resolved with PR #63, but I didn't link the issues correctly to automatically close.
