### ISSUE TITLE
Multiple landmarks appear while placing a landmark with the touchpad

### ISSUE THREAD

**Issue by aron-adc** [DCBIA-OrthoLab/Q3DCExtension#43]
Hi @luciacev @bpaniagua @jcfr 

I have uploaded two videos in the folder [DCBIA>Slicer issues>Q3DC Issue#43](https://drive.google.com/drive/u/0/folders/1uss4ubgvSOsU3Hmj1POc26l3HIVMdcxA) on Google Drive.

When adding a landmark if you do not move the cursor for some seconds while choosing the correct position, multiple landmarks appear from nothing ([Video Q3DC_Issue#43_1a](https://drive.google.com/file/d/1rBhgWlYo2hAo-_6NMaD759CVeXp7eztL/view?usp=sharing)). Invideo Q3DC_Issue43_1a, landmarks T1-1 to T1-7 were adequately added. From landmark T1-8, several landmarks are added indistinctly without doing a click on Add and before choosing the correct position. This issue is similar to #28 reported by JEHoctor

It also happens when the cursor (arrow) passes from other windows (If accidentally move my cursor outside the window where the model is, for example If the cursor passes to the inferior windows red, yellow, green) ([Video Q3DC_Issue#43_1b](https://drive.google.com/file/d/1FWHigYZI72ikLpWp2ousWPfgZP7hcOBw/view?usp=sharing)). This issue is similar to the Issue29_#2 reported for CMFreg module.  I think there is a problem with Markups.
Thank you

**Comment by luciacev** [comment]
@allemangD @bpaniagua @jcfr @aron-adc @aruellas
This issue reported by Aron in June of multiple landmarks appearing while placing a landmark has not been fixed. 
It only  seems to happen if we accidentally click twice on the Add button, then the Add button seems to keep on adding many landmarks on its own. We can always delete the extra landmarks in the Markups module, but this bug should be fixed.  Please see video shared in Google Drive.
