### ISSUE TITLE
adding one new measurement in Q3DC

### ISSUE THREAD

**Issue by aruellas** [DCBIA-OrthoLab/Q3DCExtension#7]
Would be possible to add measurements from one landmark to a line in Q3DC? In my opinion, it would be really helpful! Thanks

**Comment by fbudin69500** [comment]
@pieper , do you want to work on that since you have worked on Q3DC?

**Comment by luciacev** [comment]
Hi Steve  
You may still be in Germany, I think!!  Hope your trip is going well!
Just wanted to confirm our hangout next week on Friday Oct 16th at 11.
When possible for you, please let us know if you can help add the functionality`to measure the linear distance between a landmark to a line in Q3DC. 
Thanks so much!
Lucia

**Comment by pieper** [comment]
I took a look at the options for integrating this request - we can discuss it on the call today.  Basically we could add it as another special case in the current implementation or we could use it as a motivation for the more general solution.  Either way can work, but if we think there will be more types of measurements to add in the future we might really prefer the more general solution (that is, the CMFQuantifier approach we discussed in the past).

**Comment by pieper** [comment]
![image](https://cloud.githubusercontent.com/assets/126077/10739493/1da036ba-7bf3-11e5-805c-409727f8f2d4.png)

The drawing shows the basic layout of data for the measurements we want to support.

Here there is one patient, with two models: a maxilla and a mandible.

There are some landmarks defined as belonging to one or the other models.

Each line is defined by two different landmarks.

Each angle is defined by two different lines.

Each midpoint is defined by one line.

Each linepoint (distance from point to line) is defined by a line and a point.

@aruellas let me know if this schematically captures all the relationships you want to measure.  I'm thinking that if we have this set of relationships encoded in the Q3DC module then it can be kept in sync as landmarks are manipulated or patient datasets get swapped in-and-out of the program.

**Comment by aruellas** [comment]
Thanks Steve. I think all the measurements are included there. If it's possible to sync the landmarks to be used for different tools would be great. If we have to place the same landmarks for different tools, we can add errors due to landmarks placement. Also its a time consuming process because sometimes we have 10 or 12 landmarks for mandible and 6 or 7 landmarks for maxilla. Besides that, we have to close scene and start the new tool again because the amount of landmarks can confuse the user.

**Comment by bpaniagua** [comment]
Hi @aruellas, @fbudin69500, @juanprietob and @jbvimort are working on creating a fiducial format with all the information necessary for all the modules to share the same fiducials, as you request. We will provide an update on where that goes soon. Thank you!

**Comment by aruellas** [comment]
Thank you!!!

**Comment by jbvimort** [comment]
Hi Everyone!
I have made this quick presentation that regroup what data are currently used in each module, and a proposition for a generic data structure that could be used by every module: https://www.dropbox.com/s/kw578t4al6xq7kf/Presentation.pdf?dl=0
Feel free to make any comment on it, I would be happy to discuss about it!

**Comment by luciacev** [comment]
Thank you so much JB!
Let's discuss your pdf  presentation  for the data structure updates during our hangout Monday! I will send out  a friendly thankful email reminder for our  hangout Monday Nov 09 at 10AM! Hope  everyone has great weekend!

**Comment by pieper** [comment]
Here are some examples about putting json encoded strings into fiducial nodes and getting notifications when the data has changed.  We should follow this general strategy and see if any performance or other issues come up.

>>> f = getNode('F')
>>> f
(vtkMRMLMarkupsFiducialNode)0x1743bb650
>>> def x(*args):
...   print(args)
... 
>>> x(1,2,3)
(1, 2, 3)
>>> f.AddObserver(vtk.vtkCommand.ModifiedEvent, x)
79
>>> f.Modified()
((vtkMRMLMarkupsFiducialNode)0x1743bb650, 'ModifiedEvent')
>>> 
>>> f.SetAttribute('hoot', 'ba')
((vtkMRMLMarkupsFiducialNode)0x1743bb650, 'ModifiedEvent')
>>> f.GetAttribute('hoot')
'ba'
>>> import json
>>> js = json.dumps( {'snapped' : True, 'midpoint' : 0.5} )
>>> js
'{"snapped": true, "midpoint": 0.5}'
>>> dd = json.loads(js)
>>> dd
{u'snapped': True, u'midpoint': 0.5}
>>> f.SetAttribute('data', js)
((vtkMRMLMarkupsFiducialNode)0x1743bb650, 'ModifiedEvent')

**Comment by pieper** [comment]
I'd like to see us develop a schema for the json so that it's well documented and easy to maintain.  This is a good model to follow:

http://json-schema.org/examples.html

There are python packages for validating data.

**Comment by pieper** [comment]
Also for save/restore to mrml xml files we'll need to quote and unquote the json strings:

https://docs.python.org/2/library/urllib.html#utility-functions

**Comment by jbvimort** [comment]
Here is a first version of the new data structure in JSON, maybe this can also be used as the model to follow?

{
  "fiducials":{
    "IDofFiducial1":{
      "midpoint":{
        "IsAMidPoint":false,
        "points":null
      },
      "projection":{
        "isProjected":true,
        "indexClosestPoint":32
      },
      "roi":{
        "radius":0,
        "arrayname":null
      },
      "specificBone":null
    },
    "IDofFiducial2":{
      "midpoint":{
        "IsAMidPoint":false,
        "points":null
      },
      "projection":{
        "isProjected":true,
        "indexClosestPoint":49
      },
      "roi":{
        "radius":3,
        "arrayname":"ROI_model2"
      },
      "specificBone":null
    },
    "IDofFiducial3":{
      "midpoint":{
        "IsAMidPoint":true,
        "points":[
          "IDofFiducial1",
          "IDofFiducial2"
        ]
      },
      "projection":{
        "isProjected":false,
        "indexClosestPoint":null
      },
      "roi":{
        "radius":0,
        "arrayname":null
      },
      "specificBone":null
    },
    "IDofFiducial4":{
      "midpoint":{
        "IsAMidPoint":false,
        "points":null
      },
      "projection":{
        "isProjected":false,
        "indexClosestPoint":null
      },
      "roi":{
        "radius":0,
        "arrayname":null
      },
      "specificBone":null
    }
  },
  "planes":{
     "IDofPlane1":{
       "fiducials":[
         "IDofFiducial1",
         "IDofFiducial2",
         "IDofFiducial4"
       ],
       "hide":false,
       "adaptedOnBoundingBox":true
     }
  },
  "lines":{
    "IDofLine1":{
      "fiducials":[
        "IDofFiducial3",
        "IDofFiducial4"
      ]
    }
  },
  "connectedModel":"IDofModel",
  "hardenModel":"IDofHardenModel",
  "lastTransformation":"IDofLastTransform",
  "isMeshClean":false,
  "landmarkCreationTagEvent":"nameOfTagEvent",
  "landmarkDeplacementTagEvent":"nameOfTagEvent",
  "typeOfPropagation":"CorespondentMeshes",
  "modelToPropagate":[
    "IDofFirstPropagatedModel",
    "IDofSecondPropagatedModel"
    ]
}

**Comment by fbudin69500** [comment]
Try to be careful and be very consistent with the naming scheme (uppercase, lowercase).

**Comment by pieper** [comment]
yes, looks promising.

It would be good to try adapting one of the modules to use this approach.
Does anyone want to work on this?  If not maybe I should be the one to try
adapting Q3DC.

**Comment by jbvimort** [comment]
I'll be glad to do that! I can try with fiducialRegistration?

**Comment by fbudin69500** [comment]
@jbvimort , yes you can start with one of the extension you know the best.

**Comment by jbvimort** [comment]
Ok! I'll try to adapt SurfaceRegistration, I will give you some updates as soon as I have some results!

**Comment by pieper** [comment]
This is great J-B - a few things to consider:

* For a first implementation let's not worry too much about performance
optimizations

* I suggest that you have two update methods - one which updates the json
representation every time a fiducial is updated and one that updates the
fiducial when the json is updated.  There will need to be a state variable
so that you don't end up in a loop responding to events you create yourself.

* The markup fiducial node has attributes like Markups.MovingMarkupIndex
that you can use to optimize the update and/or decide how to respond to the
event.

Good luck!
-Steve

**Comment by bpaniagua** [comment]
@aruellas was this metric incorporated into Q3DC? Should we close and start another issue that captures what is needed better i.e. #35

**Comment by allemangD** [comment]
I am closing this issue, as all the measurements I see mentioned in this disccusion have since been added.

To be clear, we already have:

- Point-to-point midpoint
- Point-to-point distance
- Line-to-point distance (requested in this issue)
- Line-to-line angle

If this is a mistake, and there are more measurements to be added that I have missed, I think it would be best to create new issues for those measurements for improved clarity.
