### ISSUE TITLE
Linear distance between two landmarks - wrong computation

### ISSUE THREAD

**Issue by aruellas** [DCBIA-OrthoLab/Q3DCExtension#70]
I noticed some other issues while using Q3DC...
Doing measurements for ANS-Me, I thought they were a kind of small based on what I am used to get from patients in the clinic.

Fig 1: Then, I measured the distance between N and ANS (1), between ANS and Me (2), between N and Me (3). It was supposed that the S-I (vertical) component should work like 1 (N-ANS) + 2 (ANS-Me) = 3 (N-Me) but it is not even close...

Fig 2: Then, I tried another measurement to test it. I measured the linear distances from A point to B point and from B point to A point and the results were different... 

I tried an older version of Q3DC (3D Slicer 4.7.0-2016-12-12) and it worked well (correct values attached to this message), although the distance between a line and a point is not working properly that older version.

Hope it helps to improve the tool.
Thank you!

<img width="798" alt="Screen Shot correct values" src="https://user-images.githubusercontent.com/14109035/115448516-c7690d00-a1e7-11eb-8681-088ea5bb293b.png">
<img width="1284" alt="Screen Shot Figure 1" src="https://user-images.githubusercontent.com/14109035/115448546-d059de80-a1e7-11eb-8afa-47e258d0e5f1.png">
<img width="1283" alt="Screen Shot Figure 2" src="https://user-images.githubusercontent.com/14109035/115448342-9be62280-a1e7-11eb-91a7-f41b005b6854.png">

**Comment by allemangD** [comment]
Thanks for including the extra details! I'm planning to work on this Thursday.

**Comment by jcfr** [comment]
Let me know if you want some help. In the meantime, I will archive the
corresponding emails.

**Comment by luciacev** [comment]
@jcfr @allemangD @bpaniagua @aruellas 
I am working to explain further issue #70 reported by Antonio:•this issue does not occur in Slicer 4.11 stable extension SlicerCMF downloaded 3 weeks ago or the old SlicerCMF 4.1 compilation
•this issue occurs in Slicer 4.11 stable extension SlicerCMF downloaded after the changes made last week
•this issue does not occur for landmarks distances  within the same VTK model
•this issue occurs for landmarks distances  between different models
Please see attached screenshots detailing the bullet points above: 
<img width="1792" alt="Screen Shot 2021-04-21 at 11 25 37 PM" src="https://user-images.githubusercontent.com/14108157/115651659-9842c080-a2f9-11eb-92fc-59085a81c162.png">
<img width="1792" alt="Screen Shot 2021-04-21 at 11 25 40 PM" src="https://user-images.githubusercontent.com/14108157/115651683-a7c20980-a2f9-11eb-977f-8dc86b966de4.png">
<img width="1792" alt="Screen Shot 2021-04-21 at 11 25 42 PM" src="https://user-images.githubusercontent.com/14108157/115651700-b0b2db00-a2f9-11eb-86ab-53a7eedfdee0.png">
<img width="1792" alt="Screen Shot 2021-04-21 at 11 25 45 PM" src="https://user-images.githubusercontent.com/14108157/115651716-b7415280-a2f9-11eb-817f-56811c203f75.png">

Please let me know if we need to set up a Zoom meeting to clarify if you still have doubts and counting on your support. I am available today Thursday anytime except between 2-4 PM or Friday 11AM-1PM.
Thanks so much, Lucia

**Comment by aruellas** [comment]
Thank you!!!

Em qui., 22 de abr. de 2021 às 10:22, David Allemang <
***@***.***> escreveu:
