### ISSUE TITLE
option to place the landmark not on the surface is not working 

### ISSUE THREAD

**Issue by luciacev** [DCBIA-OrthoLab/Q3DCExtension#73]
@allemangD @jcfr @bpaniagua @aruellas

The box "on surface" is not working. 

Even when the box in unchecked , Q3DC does not allow users to place fiducials/landmarks that are not on the surface. they stick to the surface even when you uncheck this box.

Please allow users to place landmark  anywhere and remove the "on the surface" when needed.

Thank you so much!
Lucia

**Comment by allemangD** [comment]
Important to note this change only affects newly placed landmarks. If the first "On Surface" checkbox is unchecked, then new landmarks will not stick to the model. It will not override the "stickiness" of existing landmarks.

I've also added a tooltip to hopefully clarify this: 
![image](https://user-images.githubusercontent.com/10702931/118498435-02316880-b6f4-11eb-9e53-8468717b3d9c.png)

You can select a particular landmark, and use that second "On Surface" checkbox to toggle the "stickiness" of that particular landmark. Then you can drag the existing landmark and it will not stick to the surface.

And there is a tooltip for this checkbox also:
![image](https://user-images.githubusercontent.com/10702931/118498464-08bfe000-b6f4-11eb-9bc0-b04ef7e24d80.png)
