### ISSUE TITLE
Cannot use landmarks with name containing `'` 

### ISSUE THREAD

**Issue by luciacev** [DCBIA-OrthoLab/Q3DCExtension#75]
@allemangD @bpaniagua @jcfr @aruellas
Hi David
When we upload a fiducial list and legend or even when we just place the landmarks in Q3DC, the dropdown menu to "select landmarks" is not working and when we try to make measurements, again the dropdown menus do not show the landmarks and we cannot make measurements. Dylan shared our video recording with you.
We tested this issue both in my laptop and Dylan's that have the most updated SlicerCMF extension, so something might have changed that is now causing this issue. Dylan needs to make progress in his project this week Can you please prioritize addressing  this issue and let us know what you find out?
Thank you so much!
Lucia

**Comment by allemangD** [comment]
@luciacev clarified in an email (removing case-specific details for brevity here):

> [...] the drop down menus stopped for you after UL1 and the next landmark was UR1',  I realized the issue may have been the landmark naming  as  the Q3DC code may not like apostrophes. :-)
> 
> Please see attached the updated Landmark legend changing UR1' to UR1A and it solves your issue. [...]
> 
> [...]
> 
> [...] the issue was solved changing the name of the landmarks with an '  from for example UR1' to UR1A. I hope it is clear for you now that the issue is just that the legend cannot contain the '. It is common in landmark naming for root apex or soft tissue that users may choose to name it with an '. [...]

I am able to reproduce this; indeed attempting to place a landmark containing `'` in the name causes the landmark combobox to fail to populate. I've updated the title of this issue to reflect that.
