### ISSUE TITLE
Import list of measurement not work

### ISSUE THREAD

**Issue by HUTIN1** [DCBIA-OrthoLab/Q3DCExtension#83]
If we export a list of measurements and for another. group of patients , we want to use the same list of measurements, the" import" button or functionality is not working.

Python return this error :
![Screenshot from 2022-08-05 15-41-15](https://user-images.githubusercontent.com/72212416/183149338-08097757-ad5d-4c3b-82f2-863e4664e9d4.png)

**Comment by luciacev** [comment]
@Hutin1 @allemangD @jcfr @lucanchling @bianchijonas1
I just realized we forgot to note that this issue is regarding the AQ3DC code and not Q3DC. :-) Thanks!

**Comment by HUTIN1** [comment]
Pull request #89 solves this issue, so I close this issue
